MyTechnology/MyTechWebUı/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MyTechBusiness.Abstract;

namespace MyTechWebUı.Controllers
{
    public class ProductController : Controller
    {

        private IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int CategoryId)
        {
         
                var model = _productService.GetByCategory(CategoryId);
                return View(model);

        }
    }
}

MyTechnology/MyTechWebUı/ViewComponents/Product/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MyTechBusiness.Abstract;

namespace MyTechWebUı.ViewComponents.Product
{
    public class CategoryListViewComponent: ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            var model = _categoryService.GetAll();
            return View(model);
        }
    }
}

MyTechnology/MyTechWebUı/Views/Product/Index.cshtml
@using MyTechEntity;
@model List<Product>
@{
    ViewData["Title"] = "Ürünler";
}

<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a class="breadcrumb-item text-dark" asp-controller="Product" asp-action="Index">Shop</a>
                <span class="breadcrumb-item active">Ürün Listesi</span>
            </nav>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Kategoriler</span></h5>
            @await Component.InvokeAsync("CategoryList")
        </div>

        <div class="col-md-9 d-block">
            <div class="row pb-3">
                @*  @await Component.InvokeAsync("ProductList")*@
                @if (Model.Count == 0)
                {
                    <div class="col-md-9">
                        <div class="alert alert-info">Kategoriye Ait Ürün Bulunamadı</div>
                    </div>
                }
                else
                {
                    @foreach (var item in Model)
                    {
                        <div class="col-md-4 pb-1">
                            <div class="product-item bg-light mb-4">
                                <div class="product-img position-relative overflow-hidden">
                                    <img class="img-fluid w-100" src="~/img/@item.ImgUrl1" alt="">
                                    <div class="product-action">
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                                    </div>
                                </div>
                                <div class="text-center py-4">
                                    <a asp-controller="Home" asp-action="Details" asp-route-productId="@item.ProductId" class="h6 text-decoration-none text-center">@item.ProductName</a>
                                    <div class="d-flex align-items-center justify-content-center mt-2">
                                        <h5>@item.ProductPrice.ToString("C2")</h5>
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center mb-1">
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small class="fa fa-star text-primary mr-1"></small>
                                        <small>(99)</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>