MyTechnology/MyTechWebUı/Controllers/CartController.cs
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyTechBusiness.Abstract;
using MyTechEntity;
using MyTechWebUı.Identity;
using MyTechWebUı.Models;
using MyTechWebUı.Models.CartModels;
using MyTechWebUı.Models.OrderModels;
using Newtonsoft.Json;
using NuGet.Configuration;

namespace MyTechWebUı.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private IOrderService _orderService;
        private UserManager<User> _userManager;
        public CartController(ICartService cartService, UserManager<User> userManager, IOrderService orderService)
        {
            _cartService = cartService;
            _userManager = userManager;
            _orderService = orderService;
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            var CartItem = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(x => new CartItemModel()
                {
                    CartItemId = x.Id,
                    ProductId = x.ProductId,
                    Name = x.Product.ProductName,
                    Price = x.Product.ProductPrice,
                    ImgUrl = x.Product.ImgUrl1,
                    Quantity = x.Quantity
                }).ToList(),
            };
            return View(CartItem);
        }
        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.AddTooCart(userId, productId, quantity);
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.DeleteFromCart(userId, productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(x => new CartItemModel()
                {
                    CartItemId = x.Id,
                    ProductId = x.ProductId,
                    Name = x.Product.ProductName,
                    Price = x.Product.ProductPrice,
                    ImgUrl = x.Product.ImgUrl1,
                    Quantity = x.Quantity
                }).ToList()
            };
            return View(orderModel);
        }
        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if (ModelState.IsValid)
            {

                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);
                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(x => new CartItemModel()
                    {
                        CartItemId = x.Id,
                        ProductId = x.ProductId,
                        Name = x.Product.ProductName,
                        Price = x.Product.ProductPrice,
                        ImgUrl = x.Product.ImgUrl1,
                        Quantity = x.Quantity,
                    }).ToList()
                };

                var payment = PaymentProcess(model);

                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart();
                    return View("Success");
                }
                else
                {
                    var msg = new AlertMessage()
                    {
                        Message = $"{payment.ErrorMessage}",
                        AlertType = "danger"
                    };

                    TempData["message"] = JsonConvert.SerializeObject(msg);
                }
            }
            return View(model);


        }

        private void ClearCart()
        {
            throw new NotImplementedException();
        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();
            order.OrderNumber = new Random().Next(111111, 999999).ToString();
            order.OrderState = Order.EnumOrderState.compelet;
            order.PaymentType = Order.EnumPaymentType.CreditCard;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.UserId = userId;
            order.Email = model.Email;
            order.Phone = model.Phone;
            order.Address = model.Address;
            order.City = model.City;
            order.Note = model.Note;
            order.OrderItems = new List<MyTechEntity.OrderItem>();
            foreach (var item in model.CartModel.CartItems)
            {
                var orderItem = new MyTechEntity.OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId,
                };
                order.OrderItems.Add(orderItem);
            }
            _orderService.Create(order);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-BP81O9Yxc4LzPlFs3jPA9l3ZjZXoeUxz";
            options.SecretKey = "sandbox-nnwBlS60GJWP8JGI6a7m0QCjVZwL0y0E";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = new Random().Next(111111111, 999999999).ToString();
            request.Price = model.CartModel.TotalPrice().ToString();
            request.PaidPrice = model.CartModel.TotalPrice().ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = "B67832";
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            //paymentCard.CardNumber = "5528790000000008";
            //paymentCard.ExpireMonth = "12";
            //paymentCard.ExpireYear = "2030";
            //paymentCard.Cvc = "123";

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = model.FirstName;
            buyer.Surname = model.LastName;
            buyer.GsmNumber = "+905350000000";
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;


            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;

            foreach (var item in model.CartModel.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.ProductId.ToString();
                basketItem.Name = item.Name;
                basketItem.Category1 = "Telefon";
                string productPrice = (item.Price * item.Quantity).ToString();
                string urunFiyat = productPrice.Replace(",", ".");
                basketItem.Price = urunFiyat;
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItems.Add(basketItem);
            }
            request.BasketItems = basketItems;
            return Payment.Create(request, options);
        

        }
    }
}
//string productPrice = (item.Quantity * item.Price).ToString();
//string urunFiyat = productPrice.Replace(",", ".");
//basketItem.Price = urunFiyat;

MyTechnology/MyTechWebUı/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyTechBusiness.Abstract;
using MyTechEntity;
using MyTechWebUı.Models;
using MailKit.Net.Smtp;
using MimeKit;
using MyTechWebUı.Models.ProductModels;

namespace MyTechWebUI.Controllers
{
    public class HomeController : Controller
    {
        private IProductService _productService;
        private ICategoryService _categorytService;
        private IReviewService _reviewService;
        public HomeController(IProductService productService, ICategoryService categoryService, IReviewService reviewService)
        {
            _productService = productService;
            _categorytService = categoryService;
            _reviewService = reviewService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details(int productId)
        {
            var model = new ProductDetailViewModel
            {
                Product = _productService.GetById(productId),
                Categories = _categorytService.GetAll(),
                Reviews = _reviewService.GetAll(productId)
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Details(Review review)
        {
            if (ModelState.IsValid)
            {
                _reviewService.Add(review);
                return RedirectToAction("Details", new RouteValueDictionary(
                                        new { controller = "Home", action = "Details", productId = review.ProductId }));
            }
            return View(review);
        }
        public IActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Contact(MailRequest mailRequest)
        {
            MimeMessage mimeMessage = new MimeMessage();
            MailboxAddress mailboxAddressFrom = new MailboxAddress("User", mailRequest.ReceiverEmail);
            mimeMessage.From.Add(mailboxAddressFrom);
            MailboxAddress mailboxAddressTo = new MailboxAddress("Admin", "myblogtest10@gmail.com"); //Kime gidecek
            mimeMessage.To.Add(mailboxAddressTo);

            mimeMessage.Subject = mailRequest.Subject;
            mimeMessage.Body = new TextPart(MimeKit.Text.TextFormat.Html)
            {
                Text = mailRequest.Body
            };

            SmtpClient client = new SmtpClient();
            client.Connect("smtp.gmail.com", 587, false);
            client.Authenticate("myblogtest10@gmail.com", "xiorqayjijnwtpos");
            client.Send(mimeMessage);
            client.Disconnect(true);

            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Search(string? search)
        {
            ViewBag.Search = search;
            var model = _productService.GetAll(search);
            return View("Result", model);
        }
    }
}

MyTechnology/MyTechWebUı/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MyTechBusiness.Abstract;

namespace MyTechWebUı.Controllers
{
    public class ProductController : Controller
    {

        private IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int CategoryId)
        {
         
                var model = _productService.GetByCategory(CategoryId);
                return View(model);

        }
    }
}

MyTechnology/MyTechWebUı/ViewComponents/Home/ProductListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyTechBusiness.Abstract;
using MyTechData.Abstract;

namespace MyTechWebUı.ViewComponents.Home
{
    public class ProductListViewComponent : ViewComponent
    {
        private IProductService _productService;
        public ProductListViewComponent(IProductService productService)
        {
            _productService = productService;
        }
        public IViewComponentResult Invoke(string? search)
        {
            var model = search == null ? _productService.GetAll() : _productService.GetAll(search);
            return View(model);
        }
    }
}

MyTechnology/MyTechWebUı/Views/Home/Contact.cshtml
@model MailRequest    

@{
    ViewData["Title"] = "İletişim";
}

<div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" asp-action="Index">Home</a>
                    <span class="breadcrumb-item active">İletişim</span>
                </nav>
            </div>
        </div>
    </div>

<div class="container-fluid">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Bize Ulaş</span></h2>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5">
            <div class="contact-form bg-light p-30">
                <div id="success"></div>
                <form asp-controller="Home" asp-action="Contact" method="post" id="contactForm" novalidate="novalidate">
                    <div class="control-group">
                        <input asp-for="Name" type="text" class="form-control" id="name" placeholder="İsim"
                               required="required" data-validation-required-message="Lütfen İsim Giriniz" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input asp-for="ReceiverEmail" type="email" class="form-control" id="email" placeholder="Email"
                               required="required" data-validation-required-message="Lütfen Email Adresiniz Giriniz" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input asp-for="Subject" type="text" class="form-control" id="subject" placeholder="Konu"
                               required="required" data-validation-required-message="Lütfen Konu Giriniz" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <textarea asp-for="Body" class="form-control" rows="8" id="message" placeholder="Mesaj"
                                  required="required"
                                  data-validation-required-message="Lütfen Mesajınızı Giriniz"></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                    <div>
                        <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">
                           Mail Gönder
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <div class="bg-light p-30 mb-30">
                <iframe style="width: 100%; height: 250px;"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                        frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="bg-light p-30 mb-3">
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Adapazarı / Sakarya</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+90 534 345 67 89</p>
            </div>
        </div>
    </div>
</div>

MyTechnology/MyTechWebUı/Views/Home/Details.cshtml
@model ProductDetailViewModel
@{
    ViewData["Title"] = "ProductDetails";
}

<div class="container-fluid pb-5">
    <div class="row px-xl-5">
        <div class="col-lg-5 mb-30">
            <div id="product-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner bg-light">
                    <div class="carousel-item active">
                        <img class="w-100 h-100" src="~/img/@Model.Product.ImgUrl1" alt="Image">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                    <i class="fa fa-2x fa-angle-left text-dark"></i>
                </a>
                <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                    <i class="fa fa-2x fa-angle-right text-dark"></i>
                </a>
            </div>
        </div>
        <div class="col-lg-7 h-auto mb-30">
            <div class="h-100 bg-light p-30">
                <h3>@Model.Product.ProductName</h3>
                @* <a asp-controller="Product" asp-action="Index" asp-route-CategoryId="@Model.Category.CategoryId"><p>@Model.Categories.FirstOrDefault(c=>c.CategoryId==Model.Product.CategoryId)?.CategoryName</p></a>*@
                <div class="d-flex mb-3">
                    <div class="text-primary mr-2">
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star-half-alt"></small>
                        <small class="far fa-star"></small>
                    </div>
                </div>
                <h3 class="font-weight-semi-bold mb-4">@Model.Product.ProductPrice</h3>
                <p class="mb-4">@Model.Product.ProductTitle</p>

                <div class="d-flex align-items-center mb-4 pt-2">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <form asp-controller="Cart" asp-action="AddToCart" method="post" class="form-inline">
                            <input type="hidden" name="productId" value="@Model.Product.ProductId">
                            <div class="input-group mb-3">
                                <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" style="width:100px;">
                                <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-shopping-cart"></i> Sepete Ekle
                                </button>
                            </div>
                            </div>
                        </form>
                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Login" class="btn btn-primary px-3">Giriş Yap</a>
                    }
                </div>
                <div class="d-flex pt-2">
                    <strong class="text-dark mr-2">Paylaş:</strong>
                    <div class="d-inline-flex">
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row px-xl-5">
        <div class="col">
            <div class="bg-light p-30">
                <div class="nav nav-tabs mb-4">
                    <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Ürün Özellikleri</a>

                    <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">Yorum</a>
                </div>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="tab-pane-1">
                        <h4 class="mb-3">Ürün Özellikleri</h4>
                        @Model.Product.ProductDescription
                    </div>
                    <div class="tab-pane fade" id="tab-pane-2">
                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-4">"@Model.Product.ProductName" Ürünü için @Model.Reviews.Count() </h4>
                                @foreach (var item in Model.Reviews)
                                {

                                    <div class="media mb-4">
                                        <img src="~/img/face1.jpg" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                                        <div class="media-body">
                                            <h6><small>@item.Name - <i>@item.ReviewCreateDate.ToString("dd MMMM yyyy")</i></small></h6>
                                            <div class="text-primary mb-2">
                                                <i class="fas fa-star"></i>
                                                <i class="fas fa-star"></i>
                                                <i class="fas fa-star"></i>
                                                <i class="fas fa-star-half-alt"></i>
                                                <i class="far fa-star"></i>
                                            </div>
                                            <p>@item.Comment</p>
                                        </div>
                                    </div>
                                }

                            </div>
                            <div class="col-md-6">
                                <h4 class="mb-4">Leave a review</h4>
                                <small>E-posta adresiniz yayınlanmayacaktır. Zorunlu alanlar işaretlenir *</small>
                                <div class="d-flex my-3">
                                    <p class="mb-0 mr-2">Puan * :</p>
                                    <div class="text-primary">
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                    </div>
                                </div>
                                <form asp-controller="Home" asp-action="Details" method="post">
                                    <input asp-for="Review.ProductId" type="hidden" value="@Model.Product.ProductId" />
                                    <div class="form-group">
                                        <label asp-for="Review.Comment">Yorumunuz *</label>
                                        <textarea asp-for="Review.Comment" id="message" cols="30" rows="5" class="form-control" required="required"
                                                  data-validation-required-message="Lütfen Mesajınızı Giriniz"></textarea>
                                        <p class="help-block text-danger"></p>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Review.Name">Adınız *</label>
                                        <input asp-for="Review.Name" type="text" id="name" class="form-control" required="required" data-validation-required-message="Lütfen İsim Giriniz" />
                                        <p class="help-block text-danger"></p>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Review.Email">Mail Adresiniz *</label>
                                        <input asp-for="Review.Email" type="email" id="email" class="form-control" required="required" data-validation-required-message="Lütfen Email Adresiniz Giriniz" />
                                        <p class="help-block text-danger"></p>
                                    </div>
                                    <div class="form-group mb-0">
                                        <input type="submit" value="Yorum Yap" class="btn btn-primary px-3">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MyTechnology/MyTechWebUı/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
}
<div class="row">
    <div class="col-md-12 ">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Öne Çıkan Ürünler</span></h2>
    </div>
    @await Component.InvokeAsync("ProductList")
</div>

MyTechnology/MyTechWebUı/Views/Home/Result.cshtml
@using MyTechEntity;
@{
    ViewData["Title"] = "Ana Sayfa";
}
<div class="row">
    <div class="col-md-12 ">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Arama Sonuçları</span></h2>
        @if (Model.Count == 0)
        {
            <div class="col-md-9">
                <div class="alert alert-info">Ürün Bulunamadı</div>
            </div>
        }
        else
        {
            <div class="row">
                @await Component.InvokeAsync("ProductList",ViewBag.Search)
            </div>
        }
    </div>
</div>